// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api_Restful.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api_Restful.Core.Entities.JobTitles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.TaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Completion_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.TaskUser", b =>
                {
                    b.Property<int>("Id_User")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Task")
                        .HasColumnType("integer");

                    b.HasKey("Id_User", "Id_Task");

                    b.HasIndex("Id_Task");

                    b.ToTable("TaskUsers");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creation_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ID_User")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ID_User");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ID_JobTitle")
                        .HasColumnType("integer");

                    b.Property<int?>("ID_Token")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ID_JobTitle");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.TaskUser", b =>
                {
                    b.HasOne("Api_Restful.Core.Entities.TaskEntity", "Task")
                        .WithMany("TaskUsers")
                        .HasForeignKey("Id_Task")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_Restful.Core.Entities.User", "User")
                        .WithMany("TaskUsers")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.Token", b =>
                {
                    b.HasOne("Api_Restful.Core.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.User", b =>
                {
                    b.HasOne("Api_Restful.Core.Entities.JobTitles", "JobTitle")
                        .WithMany("User")
                        .HasForeignKey("ID_JobTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.JobTitles", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.TaskEntity", b =>
                {
                    b.Navigation("TaskUsers");
                });

            modelBuilder.Entity("Api_Restful.Core.Entities.User", b =>
                {
                    b.Navigation("TaskUsers");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
